# Generated by Django 6.0.4 on 2026-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu/')),
                ('category', models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('drinks', 'Drinks'), ('dessert', 'Dessert')], max_length=50)),
            ],
        ),
    ]
