# Generated by Django 6.0.4 on 2026-05-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
